// Storage actions.
export const LOAD_SAVED_ADDRESS = 'LOAD_SAVED_ADDRESS'
export const ADDRESS_LOADED = 'ADDRESS_LOADED'
export const SAVE_ADDRESS = 'SAVE_ADDRESS'
export const ADDRESS_SAVED = 'ADDRESS_SAVED'
export const LOAD_LIBRARY_MODE = 'LOAD_LIBRARY_MODE'
export const LIBRARY_MODE_LOADED = 'LIBRARY_MODE_LOADED'
export const SAVE_LIBRARY_MODE = 'SAVE_LIBRARY_MODE'
export const LIBRARY_MODE_SAVED = 'LIBRARY_MODE_SAVED'
