// Artist art.
export const GET_ARTIST_ART = 'GET_ARTIST_ART'
export const ARTIST_ART_RECEIVED = 'ARTIST_ART_RECEIVED'
export const LOAD_ARTIST_ART = 'LOAD_ARTIST_ART'
export const ARTIST_ART_LOADED = 'ARTIST_ART_LOADED'

