// Player controls.
export const PLAY_PAUSE = 'PLAY_PAUSE'
export const PLAY_NEXT = 'PLAY_NEXT'
export const PLAY_PREVIOUS = 'PLAY_PREVIOUS'
export const SEEK = 'SEEK'
export const START_PROGRESS_UPDATE = 'START_PROGRESS_UPDATE'
export const STOP_PROGRESS_UPDATE = 'STOP_PROGRESS_UPDATE'
export const SET_VOLUME = 'SET_VOLUME'
export const SET_CONSUME = 'SET_CONSUME'
export const SET_REPEAT = 'SET_REPEAT'
export const SET_RANDOM = 'SET_RANDOM'
export const CROSSFADE = 'CROSSFADE'
export const SET_SINGLE = 'SET_SINGLE'
export const SET_REPLAY_GAIN_MODE = 'SET_REPLAY_GAIN_MODE'
